In [2]:
import os
import pandas as pd
import plotly.express as px

PROJ = '/home/jake/Documents/research/hud/'
os.chdir(PROJ)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [23]:
raw_df = pd.read_csv('data/0_raw/hud_2021_raw.csv')
county_df = raw_df.copy()
county_df['fips'] = county_df['fips2010'].apply(lambda x: str(x).split('9999')[0])
county_df.sort_values('fips')


state_df = raw_df.groupby(['state_alpha'])['rent50_1','pop2017'].agg('mean').sort_values('rent50_1',ascending=False)

,Unnamed: 0,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub21,areaname21,county,cousub,cntyname,name,pop2017,hu2017,state_alpha,fips
2000,2000,109999999,479,556,634,789,925,1,NCNTY01099N01099,"Monroe County, AL",99,99999,Monroe County,Monroe County,21745,11375,AL,10
218,218,100999999,891,950,1093,1421,1537,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",9,99999,Blount County,Blount County,57665,24161,AL,100
692,692,1000199999,932,964,1131,1619,1894,10,METRO20100M20100,"Dover, DE MSA",1,99999,Kent County,Kent County,173145,69506,DE,10001
1305,1305,1000399999,970,1121,1358,1689,1935,10,METRO37980M37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",3,99999,New Castle County,New Castle County,555035,221003,DE,10003
1592,1592,1000599999,703,803,1058,1432,1651,10,METRO41540N10005,"Sussex County, DE HUD Metro FMR Area",5,99999,Sussex County,Sussex County,215550,132980,DE,10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,1951,901567400,868,870,1102,1391,1803,9,METRO49340N09015,"Windham County, CT HUD Metro FMR Area",15,67400,Windham County,Scotland town,1690,662,CT,901567400
1952,1952,901573420,868,870,1102,1391,1803,9,METRO49340N09015,"Windham County, CT HUD Metro FMR Area",15,73420,Windham County,Sterling town,3750,1284,CT,901573420
1953,1953,901575870,868,870,1102,1391,1803,9,METRO49340N09015,"Windham County, CT HUD Metro FMR Area",15,75870,Windham County,Thompson town,9300,4112,CT,901575870
1954,1954,901586790,868,870,1102,1391,1803,9,METRO49340N09015,"Windham County, CT HUD Metro FMR Area",15,86790,Windham County,Windham town,24840,9692,CT,901586790
1955,1955,901588190,868,870,1102,1391,1803,9,METRO49340N09015,"Windham County, CT HUD Metro FMR Area",15,88190,Windham County,Woodstock town,7825,3513,CT,901588190

/tmp/ipykernel_93570/725036410.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  state_df = raw_df.groupby(['state_alpha'])['rent50_1','pop2017'].agg('mean').sort_values('rent50_1',ascending=False)

In [15]:
raw_df

,Unnamed: 0,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub21,areaname21,county,cousub,cntyname,name,pop2017,hu2017,state_alpha
0,0,4805999999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",59,99999,Callahan County,Callahan County,13660,6637,TX
1,1,4825399999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",253,99999,Jones County,Jones County,19970,7292,TX
2,2,4844199999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",441,99999,Taylor County,Taylor County,135370,56978,TX
3,3,7200399999,401,414,472,602,720,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,99999,Aguada Municipio,Aguada Municipio,39470,17385,PR
4,4,7200599999,401,414,472,602,720,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,99999,Aguadilla Municipio,Aguadilla Municipio,55720,27301,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,4761,7213399999,386,395,450,599,666,72,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,133,99999,Santa Isabel Municipio,Santa Isabel Municipio,22475,9417,PR
4762,4762,7214799999,386,395,450,599,666,72,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,147,99999,Vieques Municipio,Vieques Municipio,8930,5101,PR
4763,4763,7801099999,926,945,1154,1435,1565,78,NCNTY78010N78010,"St. Croix Island, VI",10,99999,St. Croix,St. Croix,53234,25275,VI
4764,4764,7802099999,1230,1458,1812,2254,2457,78,NCNTY78020N78020,"St. John Island, VI",20,99999,St. John,St. John,4197,3453,VI
4765,4765,7803099999,866,1044,1307,1626,1772,78,NCNTY78030N78030,"St. Thomas Island, VI",30,99999,St. Thomas,St. Thomas,51181,27173,VI